[[bond]]
source = "tpknam1qrncel8ulawr2r6vle46dlqz446up6hnwe8euv3a7ja4aaffuz5ej4z0skc"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "280"

[bond.signatures]
tpknam1qrncel8ulawr2r6vle46dlqz446up6hnwe8euv3a7ja4aaffuz5ej4z0skc = "signam1qqycpd0kln9r9zs3thztj40h6k5hlqydf30xfk0jtjce8jf48n65dme777pckd9jgdptv90susrmh0wu0s30ttsyw4dy8du80u4akfs9em3ku4"
